apiVersion: v1
kind: Service
metadata:
  name: codis-proxy
  labels:
    service: codis-proxy
spec:
  ports:
    - name: tcpaddr
      port: 19000
    - name: httpaddr
      port: 11000
  selector:
    name: codis-proxy
