apiVersion: v1
kind: ReplicationController
metadata:
  name: flume-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flume-1
        service: flume
    spec:
      imagePullSecrets:
        - name: bfdreg 
      containers:
        - name: server
          image: daocloud.io/zhengbo0/flume
          ports:
            - containerPort: 44444
