apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
  labels:
    component: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hello
    spec:
      containers:
      - name: hello
        image: yancey1989/hello:1.0
        ports:
        - containerPort: 8080
